spring:
  datasource:
    url: jdbc:mysql:///weibo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.demo.dao: debug
